spring:
  shardingsphere:
    props:
      sql:
        show:
          true
    datasource:
      names: write,read
      write:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/redoordb?user=root&password=123456&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
      read:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/redoordb?user=root&password=123456&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
    sharding:
      defaultDatabaseStrategy:
        hint:
          algorithmClassName: com.hw.demo.services.DatasourceRoutingAlgorithm
      tables:
        write:
          actualDataNodes: write.t_user_base_info
        read:
          actualDataNodes: read.t_user_base_info
      defaultTableStrategy:
        none:
          any:
  redis:
    host: 127.0.0.1
    port: 6379